#!/bin/bash

FormatFile="/tmp/inform.txt"
FolderRoot="$1"
CSVFile="$2"
ExtList=".*\.\(mp4\|m4v\|m4p\|mkv\|avi\|asf\|wmv\|flv\|vob\|ts\|mpg\|mpeg\|mts\|m2ts\|webm\|ogv\|mov\|3gp\|3g2\)"

function cleanup () 
{
   rm "$FormatFile"
}
trap "cleanup"  EXIT

mi=$(which mediainfo)
if [ $? -eq 1 ]; then
   echo "Failed to locate mediainfo on this system. This script won't work without it."
   exit;
fi 

# Create the Format file used by mediainfo
echo 'General;""%CompleteName%"", %FileExtension%, %FileSize%, %Duration/String3%, ' > "$FormatFile"
echo 'Video;%Width%, %Height%, %FrameRate%, %DisplayAspectRatio/String%' >> "$FormatFile"

# Create CSV file with headers
echo "filename, ext, size, duration, width, height, fps, aspect" > "$CSVFile"

find "$FolderRoot" -type f -iregex "$ExtList" -exec "$mi" --Inform="file://$FormatFile" {} \; >> "$CSVFile"

exit;
